/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.provys.provysdb.api;

import java.sql.Array;
import java.sql.Blob;
import java.sql.CallableStatement;
import java.sql.Clob;
import java.sql.Connection;
import java.sql.DatabaseMetaData;
import java.sql.NClob;
import java.sql.PreparedStatement;
import java.sql.SQLClientInfoException;
import java.sql.SQLException;
import java.sql.SQLWarning;
import java.sql.SQLXML;
import java.sql.Savepoint;
import java.sql.Statement;
import java.sql.Struct;
import java.util.Map;
import java.util.Properties;
import java.util.concurrent.Executor;

/**
 *
 * @author stehlik
 */
public interface ProvysConnection extends Connection {

    @Override
    void abort(Executor executor) throws SQLException;

    @Override
    void clearWarnings() throws SQLException;

    @Override
    void close() throws SQLException;

    @Override
    void commit() throws SQLException;

    @Override
    Array createArrayOf(String typeName, Object[] elements) throws SQLException;

    @Override
    Blob createBlob() throws SQLException;

    @Override
    Clob createClob() throws SQLException;

    @Override
    NClob createNClob() throws SQLException;

    @Override
    SQLXML createSQLXML() throws SQLException;

    @Override
    Statement createStatement() throws SQLException;

    @Override
    Statement createStatement(int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    Statement createStatement(int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    @Override
    Struct createStruct(String typeName, Object[] attributes) throws SQLException;

    @Override
    boolean getAutoCommit() throws SQLException;

    @Override
    String getCatalog() throws SQLException;

    @Override
    String getClientInfo(String name) throws SQLException;

    @Override
    Properties getClientInfo() throws SQLException;

    @Override
    int getHoldability() throws SQLException;

    @Override
    DatabaseMetaData getMetaData() throws SQLException;

    @Override
    int getNetworkTimeout() throws SQLException;

    @Override
    String getSchema() throws SQLException;

    @Override
    int getTransactionIsolation() throws SQLException;

    @Override
    Map<String, Class<?>> getTypeMap() throws SQLException;

    @Override
    SQLWarning getWarnings() throws SQLException;

    @Override
    boolean isClosed() throws SQLException;

    @Override
    boolean isReadOnly() throws SQLException;

    @Override
    boolean isValid(int timeout) throws SQLException;

    @Override
    boolean isWrapperFor(Class<?> iface) throws SQLException;

    @Override
    String nativeSQL(String sql) throws SQLException;

    @Override
    CallableStatement prepareCall(String sql) throws SQLException;

    @Override
    CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    CallableStatement prepareCall(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    @Override
    PreparedStatement prepareStatement(String sql) throws SQLException;

    @Override
    PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency) throws SQLException;

    @Override
    PreparedStatement prepareStatement(String sql, int resultSetType, int resultSetConcurrency, int resultSetHoldability) throws SQLException;

    @Override
    PreparedStatement prepareStatement(String sql, int autoGeneratedKeys) throws SQLException;

    @Override
    PreparedStatement prepareStatement(String sql, int[] columnIndexes) throws SQLException;

    @Override
    PreparedStatement prepareStatement(String sql, String[] columnNames) throws SQLException;

    @Override
    void releaseSavepoint(Savepoint savepoint) throws SQLException;

    @Override
    void rollback() throws SQLException;

    @Override
    void rollback(Savepoint savepoint) throws SQLException;

    @Override
    void setAutoCommit(boolean autoCommit) throws SQLException;

    @Override
    void setCatalog(String catalog) throws SQLException;

    @Override
    void setClientInfo(String name, String value) throws SQLClientInfoException;

    @Override
    void setClientInfo(Properties properties) throws SQLClientInfoException;

    @Override
    void setHoldability(int holdability) throws SQLException;

    @Override
    void setNetworkTimeout(Executor executor, int milliseconds) throws SQLException;

    @Override
    void setReadOnly(boolean readOnly) throws SQLException;

    @Override
    Savepoint setSavepoint() throws SQLException;

    @Override
    Savepoint setSavepoint(String name) throws SQLException;

    @Override
    void setSchema(String schema) throws SQLException;

    @Override
    void setTransactionIsolation(int level) throws SQLException;

    @Override
    void setTypeMap(Map<String, Class<?>> map) throws SQLException;

    @Override
    <T> T unwrap(Class<T> iface) throws SQLException;
    
}
